repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shfmt
      - id: shellcheck
  - repo: local
    hooks:
      #      - id: lint
      #        name: Automatically fix linter issues
      #        entry: pls fix:lint
      #        files: ^.*\.(ts|js)$
      #        pass_filenames: false
      #        language: system

      - id: coverage
        name: Test and Coverage
        entry: pls test
        files: ^.*\.(ts|js)$
        pass_filenames: false
        language: system

      - id: build
        name: Build
        entry: pls build
        files: ^.*\.(ts|js)$
        pass_filenames: false
        language: system

      - id: json-fmt
        name: Format JSON with prettier
        entry: pls fmt:json
        files: ^.*\.json$
        pass_filenames: false
        language: system

      - id: yaml-fmt
        name: Format YAML with prettier
        entry: pls fmt:yaml
        files: ^.*\.(yaml|yml)$
        pass_filenames: false
        language: system

      - id: md-fmt
        name: Format Markdown with prettier
        entry: pls fmt:md
        files: ^.*\.(MD|md)$
        pass_filenames: false
        language: system

      - id: nixpkgs-fmt
        name: Format NIX files
        entry: pls fmt:nix
        files: ^.*\.nix$
        language: system
        pass_filenames: false
#      - id: gitlint-linter
#        name: Lints Gitlint to conform to atomi_release.yaml
#        entry: sg gitlint
#        files: (atomi_release.yaml|.gitlint)
#        language: system
#        pass_filenames: false

#      - id: cfg-scripts
#        name: Configure Scripts
#        entry: pls cfg:scripts
#        files: ^.*\.sh$
#        pass_filenames: false
#        language: system
